/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.sisteminformasi.view;

/**
 *
 * @author Naufal Zayn M
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setSize(640,640);
        ceklis1.setVisible(false);
        ceklis2.setVisible(false);
        loginAdmin.setVisible(false);
        loginkaryawan.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginAdmin = new javax.swing.JPanel();
        submit2 = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        loginkaryawan = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        loginawal = new javax.swing.JPanel();
        ceklis2 = new javax.swing.JLabel();
        ceklis1 = new javax.swing.JLabel();
        karywan = new javax.swing.JLabel();
        adm = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/sisteminformasi/view/submit2.png"))); // NOI18N
        loginAdmin.add(submit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/sisteminformasi/view/submit11.png"))); // NOI18N
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
        });
        loginAdmin.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        loginAdmin.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 200, 20));

        jLabel10.setFont(new java.awt.Font("Nevis", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(43, 77, 115));
        jLabel10.setText("Username Admin");
        loginAdmin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 70));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        loginAdmin.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 200, 20));

        jLabel11.setFont(new java.awt.Font("Nevis", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(43, 77, 115));
        jLabel11.setText("Password");
        loginAdmin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, 70));

        jLabel12.setForeground(new java.awt.Color(43, 77, 115));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/sisteminformasi/view/login3.png"))); // NOI18N
        loginAdmin.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(loginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 640));

        loginkaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        loginkaryawan.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 200, 20));

        jLabel8.setFont(new java.awt.Font("Nevis", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(43, 77, 115));
        jLabel8.setText("Username Karyawan");
        loginkaryawan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 70));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        loginkaryawan.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 200, 20));

        jLabel9.setFont(new java.awt.Font("Nevis", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(43, 77, 115));
        jLabel9.setText("Password");
        loginkaryawan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, 70));

        jLabel7.setForeground(new java.awt.Color(43, 77, 115));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/sisteminformasi/view/login3.png"))); // NOI18N
        loginkaryawan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(loginkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 640));

        loginawal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ceklis2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/sisteminformasi/view/ceklis.png"))); // NOI18N
        ceklis2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ceklis2MouseClicked(evt);
            }
        });
        loginawal.add(ceklis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        ceklis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/sisteminformasi/view/ceklis.png"))); // NOI18N
        ceklis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ceklis1MouseClicked(evt);
            }
        });
        loginawal.add(ceklis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        karywan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/sisteminformasi/view/kar.png"))); // NOI18N
        karywan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                karywanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                karywanMouseExited(evt);
            }
        });
        loginawal.add(karywan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        adm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/sisteminformasi/view/adm.png"))); // NOI18N
        adm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admMouseExited(evt);
            }
        });
        loginawal.add(adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Nevis", 1, 18)); // NOI18N
        jLabel4.setText("Admin");
        loginawal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        jLabel5.setFont(new java.awt.Font("Nevis", 1, 18)); // NOI18N
        jLabel5.setText("Karyawan");
        loginawal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/sisteminformasi/view/login3.png"))); // NOI18N
        loginawal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(loginawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void karywanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karywanMouseEntered
        // TODO add your handling code here:
        ceklis1.setVisible(true);
    }//GEN-LAST:event_karywanMouseEntered

    private void karywanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karywanMouseExited
        // TODO add your handling code here:
        ceklis1.setVisible(false);
    }//GEN-LAST:event_karywanMouseExited

    private void ceklis1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceklis1MouseClicked
        // TODO add your handling code here:
        loginawal.setVisible(false);
        loginkaryawan.setVisible(true);
    }//GEN-LAST:event_ceklis1MouseClicked

    private void admMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMouseEntered
        // TODO add your handling code here:
        ceklis2.setVisible(true);
    }//GEN-LAST:event_admMouseEntered

    private void admMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMouseExited
        // TODO add your handling code here:
        ceklis2.setVisible(false);
    }//GEN-LAST:event_admMouseExited

    private void ceklis2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceklis2MouseClicked
        // TODO add your handling code here:
        loginawal.setVisible(false);
        loginAdmin.setVisible(true);
    }//GEN-LAST:event_ceklis2MouseClicked

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        // TODO add your handling code here:
        submit.setVisible(false);
        submit2.setVisible(true);
    }//GEN-LAST:event_submitMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adm;
    private javax.swing.JLabel ceklis1;
    private javax.swing.JLabel ceklis2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel karywan;
    private javax.swing.JPanel loginAdmin;
    private javax.swing.JPanel loginawal;
    private javax.swing.JPanel loginkaryawan;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel submit2;
    // End of variables declaration//GEN-END:variables
}
